#Docusign Integration Configuration
hmac:
  docusignSignatureHeader: x-docusign-signature-1
  docusignSecret: uXeKjhJIdzaKnJInCWq2jKbCPvIpUuPBLOV7OMKzRCs=
  filterPattern: "/users/*"
  enabled: true

#Actuator Management Endpoints Configuration

management:
  health:
    diskspace:
      enabled: false
  endpoint:
    env:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'

server:
  port: 9081

